#
# the value of the INSTANCE_NAME must match the docker-compose project name (default to "productdb")
# the value of the INSTANCE_CONFIG is used to identify the correct environment file located at
#   deploy/docker/env/env.INSTANCE_CONFIG (default to demo)
#
version: '3'

services:
  redis:
    restart: always
    image: redis:latest
    command: redis-server --appendonly yes
    networks:
      - internal

  database:
    image: productdb/database:latest
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile-postgres
    env_file: deploy/docker/env/env.${INSTANCE_CONFIG:-demo}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    networks:
      - internal

  build_deps:
    image: productdb/build_deps:latest
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile-build_deps
    env_file: deploy/docker/env/env.${INSTANCE_CONFIG:-demo}
    volumes:
      - static_files:/var/www/productdb/static
      - ssl_files:/var/www/productdb/ssl
    networks:
      - default
      - internal

  camera:
    restart: always
    image: productdb/camera:latest
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile-camera
    env_file: deploy/docker/env/env.${INSTANCE_CONFIG:-demo}
    networks:
      - internal
    volumes:
      - data:/var/www/productdb/data
    depends_on:
      - build_deps
      - database
      - redis

  beat:
    restart: always
    image: productdb/beat:latest
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile-beat
    env_file: deploy/docker/env/env.${INSTANCE_CONFIG:-demo}
    networks:
      - default
      - internal
    volumes:
      - data:/var/www/productdb/data
    depends_on:
      - build_deps
      - database
      - redis

  worker:
    restart: always
    image: productdb/worker:latest
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile-worker
    env_file: deploy/docker/env/env.${INSTANCE_CONFIG:-demo}
    networks:
      - default
      - internal
    volumes:
      - data:/var/www/productdb/data
    depends_on:
      - build_deps
      - database
      - redis
      - beat

  web:
    restart: always
    image: productdb/web:latest
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile-web
    env_file: deploy/docker/env/env.${INSTANCE_CONFIG:-demo}
    networks:
      - default
      - internal
    volumes:
      - data:/var/www/productdb/data
    depends_on:
      - build_deps
      - database
      - redis

  nginx:
    restart: always
    image: productdb/nginx
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile-nginx
    env_file: deploy/docker/env/env.${INSTANCE_CONFIG:-demo}
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    networks:
      - default
    volumes:
      - static_files:/var/www/productdb/static:ro
      - ssl_files:/var/www/productdb/ssl:ro
    depends_on:
      - build_deps
      - web

networks:
  default:
  internal:
    driver: bridge

volumes:
  postgres_data:
  static_files:
  ssl_files:
  data:
  postgres_backup:
