---
- hosts: staging
  gather_facts: True
  vars:
    site_name: "<hostname>"
    site_directory: "/var/www"
    site_user: "<user for page>"
    site_group: "www-data"
    system_source: "git"
    site_source: "https://github.com/hoelsner/product-database.git"
    site_source_branch: "master"
    dbname: productdb
    deployment_type: production
    ignore_allowedhosts: False

  tasks:
   - include: ../appliance/appliance-provision-tasks.yml

   - debug: msg="System {{ inventory_hostname }} is reachable at {{ ansible_all_ipv4_addresses }}"