---
################################################################
# configure postgres
################################################################
  - name: register postgres configuration flag
    stat: path={{ site_directory }}/{{ site_name }}/database/postgres_configured
    register: db_configured
  - name: start postgresql service for configuration
    service: name=postgresql state=started enabled=yes
    sudo: true
  - name: configure postgres database for website
    shell: ./build-scripts/appliance/script/configure_postgres.sh {{ site_name }} {{ dbname }} {{ site_user }} {{ site_group }}
    sudo: true
    args:
      chdir: "{{ site_directory }}/{{ site_name }}/source/"
    when: db_configured.stat.exists == False
  - name: stop postgresql service
    service: name=postgresql state=stopped enabled=yes
    sudo: true
  - name: create configuration flag in the database folder
    file: path={{ site_directory }}/{{ site_name }}/database/postgres_configured state=touch mode="u=rw,g=r,o=r"