---
  #
  # add LDAP configuration values
  - name: set LDAP authentication configuration value
    become: true
    lineinfile:
      dest: /etc/productdb/productdb
      regexp: '^PDB_LDAP_ENABLE='
      line: 'PDB_LDAP_ENABLE=1'
    when: enable_ldap == true
  - name: set LDAP server URL configuration value
    become: true
    lineinfile:
      dest: /etc/productdb/productdb
      regexp: '^PDB_LDAP_SERVER_URL='
      line: 'PDB_LDAP_SERVER_URL={{ ldap_server_url }}'
    when: enable_ldap == true
  - name: set LDAP bind DN
    become: true
    lineinfile:
      dest: /etc/productdb/productdb
      regexp: '^PDB_LDAP_BIND_DN='
      line: 'PDB_LDAP_BIND_DN={{ ldap_bind_dn }}'
    when: enable_ldap == true
  - name: set LDAP bind password
    become: true
    lineinfile:
      dest: /etc/productdb/productdb
      regexp: '^PDB_LDAP_BIND_PASSWORD='
      line: 'PDB_LDAP_BIND_PASSWORD={{ ldap_bind_password }}'
    when: enable_ldap == true
  - name: set LDAP user-search parameter
    become: true
    lineinfile:
      dest: /etc/productdb/productdb
      regexp: '^PDB_LDAP_USER_SEARCH='
      line: 'PDB_LDAP_USER_SEARCH={{ ldap_user_search }}'
    when: enable_ldap == true
  - name: set LDAP group-search parameter
    become: true
    lineinfile:
      dest: /etc/productdb/productdb
      regexp: '^PDB_LDAP_GROUP_SEARCH='
      line: 'PDB_LDAP_GROUP_SEARCH={{ ldap_group_search }}'
    when: enable_ldap == true
  - name: set LDAP require-group parameter
    become: true
    lineinfile:
      dest: /etc/productdb/productdb
      regexp: '^PDB_LDAP_REQUIRE_GROUP='
      line: 'PDB_LDAP_REQUIRE_GROUP={{ ldap_require_group }}'
    when: enable_ldap == true
