---
  #
  # LDAP configuration for GUNICORN
  #
  - name: set LDAP server URL
    become: true
    replace:
      dest=/etc/systemd/system/productdb-gunicorn.service
      regexp='__PDB_LDAP_SERVER_URL__'
      replace={{ ldap_server_url }}
    when: enable_ldap == true
  - name: set LDAP bind DN
    become: true
    replace:
      dest=/etc/systemd/system/productdb-gunicorn.service
      regexp='__PDB_LDAP_BIND_DN__'
      replace={{ ldap_bind_dn }}
    when: enable_ldap == true
  - name: set LDAP bind password
    become: true
    replace:
      dest=/etc/systemd/system/productdb-gunicorn.service
      regexp='__PDB_LDAP_BIND_PASSWORD__'
      replace={{ ldap_bind_password }}
    when: enable_ldap == true
  - name: set LDAP user-search parameter
    become: true
    replace:
      dest=/etc/systemd/system/productdb-gunicorn.service
      regexp='__PDB_LDAP_USER_SEARCH__'
      replace={{ ldap_user_search }}
    when: enable_ldap == true
  - name: set LDAP group-search parameter
    become: true
    replace:
      dest=/etc/systemd/system/productdb-gunicorn.service
      regexp='__PDB_LDAP_GROUP_SEARCH__'
      replace={{ ldap_group_search }}
    when: enable_ldap == true
  - name: set LDAP require-group parameter
    become: true
    replace:
      dest=/etc/systemd/system/productdb-gunicorn.service
      regexp='__PDB_LDAP_REQUIRE_GROUP__'
      replace={{ ldap_require_group }}
    when: enable_ldap == true

  #
  # LDAP configuration for CELERY WORKER service
  #
  - name: set LDAP server URL
    become: true
    replace:
      dest=/etc/systemd/system/productdb-celeryworker.service
      regexp='__PDB_LDAP_SERVER_URL__'
      replace={{ ldap_server_url }}
    when: enable_ldap == true
  - name: set LDAP bind DN
    become: true
    replace:
      dest=/etc/systemd/system/productdb-celeryworker.service
      regexp='__PDB_LDAP_BIND_DN__'
      replace={{ ldap_bind_dn }}
    when: enable_ldap == true
  - name: set LDAP bind password
    become: true
    replace:
      dest=/etc/systemd/system/productdb-celeryworker.service
      regexp='__PDB_LDAP_BIND_PASSWORD__'
      replace={{ ldap_bind_password }}
    when: enable_ldap == true
  - name: set LDAP user-search parameter
    become: true
    replace:
      dest=/etc/systemd/system/productdb-celeryworker.service
      regexp='__PDB_LDAP_USER_SEARCH__'
      replace={{ ldap_user_search }}
    when: enable_ldap == true
  - name: set LDAP group-search parameter
    become: true
    replace:
      dest=/etc/systemd/system/productdb-celeryworker.service
      regexp='__PDB_LDAP_GROUP_SEARCH__'
      replace={{ ldap_group_search }}
    when: enable_ldap == true
  - name: set LDAP require-group parameter
    become: true
    replace:
      dest=/etc/systemd/system/productdb-celeryworker.service
      regexp='__PDB_LDAP_REQUIRE_GROUP__'
      replace={{ ldap_require_group }}
    when: enable_ldap == true

  #
  # LDAP configuration for CELERYCAM service
  #
  - name: set LDAP server URL
    become: true
    replace:
      dest=/etc/systemd/system/productdb-celerycamera.service
      regexp='__PDB_LDAP_SERVER_URL__'
      replace={{ ldap_server_url }}
    when: enable_ldap == true
  - name: set LDAP bind DN
    become: true
    replace:
      dest=/etc/systemd/system/productdb-celerycamera.service
      regexp='__PDB_LDAP_BIND_DN__'
      replace={{ ldap_bind_dn }}
    when: enable_ldap == true
  - name: set LDAP bind password
    become: true
    replace:
      dest=/etc/systemd/system/productdb-celerycamera.service
      regexp='__PDB_LDAP_BIND_PASSWORD__'
      replace={{ ldap_bind_password }}
    when: enable_ldap == true
  - name: set LDAP user-search parameter
    become: true
    replace:
      dest=/etc/systemd/system/productdb-celerycamera.service
      regexp='__PDB_LDAP_USER_SEARCH__'
      replace={{ ldap_user_search }}
    when: enable_ldap == true
  - name: set LDAP group-search parameter
    become: true
    replace:
      dest=/etc/systemd/system/productdb-celerycamera.service
      regexp='__PDB_LDAP_GROUP_SEARCH__'
      replace={{ ldap_group_search }}
    when: enable_ldap == true
  - name: set LDAP require-group parameter
    become: true
    replace:
      dest=/etc/systemd/system/productdb-celerycamera.service
      regexp='__PDB_LDAP_REQUIRE_GROUP__'
      replace={{ ldap_require_group }}
    when: enable_ldap == true

