---
  #
  # add Sentry configuration values
  - name: set enable sentry configuration value
    become: true
    lineinfile:
      dest: /etc/productdb/productdb
      regexp: '^PDB_ENABLE_SENTRY='
      line: 'PDB_ENABLE_SENTRY=1'
    when: enable_sentry == true
  - name: set sentry DSN configuration value
    become: true
    lineinfile:
      dest: /etc/productdb/productdb
      regexp: '^PDB_SENTRY_DSN='
      line: 'PDB_SENTRY_DSN={{ sentry_dsn }}'
    when: enable_sentry == true
