---
  - name: restart nginx service
    service: name=nginx state=restarted enabled=yes
    become: true
  - name: restart redis service
    service: name=redis-server state=restarted enabled=yes
    become: true
  - name: restart postgresql service
    service: name=postgresql state=restarted enabled=yes
    ignore_errors: yes
    become: true
  - name: restart gunicorn service
    service: name=productdb-gunicorn state=restarted enabled=yes
    become: true
  - name: restart celeryworker service
    service: name=productdb-celeryworker state=restarted enabled=yes
    become: true
  - name: restart celerybeat service
    service: name=productdb-celerybeat state=restarted enabled=yes
    become: true
  - name: restart celerycam service
    service: name=productdb-celerycamera state=restarted enabled=yes
    become: true