---
  - name: start nginx service
    service: name=nginx state=started enabled=yes
    ignore_errors: yes
    sudo: true
  - name: start redis service
    service: name=redis-server state=started enabled=yes
    ignore_errors: yes
    sudo: true
  - name: start postgresql service
    service: name=postgresql state=started enabled=yes
    ignore_errors: yes
    sudo: true
  - name: start gunicorn service
    service: name=productdb-gunicorn state=started enabled=yes
    ignore_errors: yes
    sudo: true
  - name: start celeryworker service
    service: name=productdb-celeryworker state=started enabled=yes
    ignore_errors: yes
    sudo: true
  - name: start celerycam service
    service: name=productdb-celerycamera state=started enabled=yes
    ignore_errors: yes
    sudo: true