---
  - name: stop celeryworker service
    service: name=productdb-celeryworker state=stopped enabled=yes
    ignore_errors: yes
    sudo: true
  - name: stop celerycam service
    service: name=productdb-celerycamera state=stopped enabled=yes
    ignore_errors: yes
    sudo: true
  - name: stop postgresql service
    service: name=postgresql state=stopped enabled=yes
    ignore_errors: yes
    sudo: true
  - name: stop nginx service
    service: name=nginx state=stopped enabled=yes
    ignore_errors: yes
    sudo: true
  - name: stop redis service
    service: name=redis-server state=stopped enabled=yes
    ignore_errors: yes
    sudo: true
  - name: stop gunicorn service
    service: name=productdb-gunicorn state=stopped enabled=yes
    ignore_errors: yes
    sudo: true